service: warmup-plugin
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "arn:aws:lambda:us-east-1:*"
plugins:
  - serverless-plugin-warmup
custom:
  warmup:
    default:
      enabled: true # Whether to warm up functions by default or not
      memorySize: 256
      name: warmer-default
      role: IamRoleLambdaExecution
      vpc: false
      events:
        - schedule: 'cron(0/2 8-17 ? * MON-FRI *)' # Run WarmUp every 5 minutes Mon-Fri between 8:00am and 5:55pm (UTC)
      timeout: 20
      tracing: true
      prewarm: true # Run WarmUp immediately after a deploymentlambda
      concurrency: 1 # Warm up 5 concurrent instances
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
    warmup:
      default:
        enabled: dev
